# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-04 19:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domositeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scalarvaluetype',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scalarvaluetypes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propertytypes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertychange',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='domositeapp.Device'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domositeapp.PropertyType'),
        ),
        migrations.AddField(
            model_name='property',
            name='related_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domositeapp.Device'),
        ),
        migrations.AddField(
            model_name='logaction',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='house',
            name='server',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domositeapp.Server'),
        ),
        migrations.AddField(
            model_name='house',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='houses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enumvaluetype',
            name='choices',
            field=models.ManyToManyField(to='domositeapp.Choice'),
        ),
        migrations.AddField(
            model_name='enumvaluetype',
            name='default_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='domositeapp.Choice'),
        ),
        migrations.AddField(
            model_name='enumvaluetype',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enumvaluetypes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='division',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domositeapp.Area'),
        ),
        migrations.AddField(
            model_name='division',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='properties',
            field=models.ManyToManyField(to='domositeapp.PropertyType'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devicetypes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domositeapp.DeviceType'),
        ),
        migrations.AddField(
            model_name='device',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domositeapp.Division'),
        ),
        migrations.AddField(
            model_name='device',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domositeapp.Server'),
        ),
        migrations.AddField(
            model_name='device',
            name='services',
            field=models.ManyToManyField(blank=True, to='domositeapp.CustomService'),
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customservice',
            name='core_service_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='domositeapp.Service'),
        ),
        migrations.AddField(
            model_name='customservice',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choice',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enumchoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='area',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domositeapp.House'),
        ),
        migrations.AddField(
            model_name='area',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together=set([('coap_address', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='scalarvaluetype',
            unique_together=set([('name', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='propertytype',
            unique_together=set([('name', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together=set([('related_device', 'property_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='house',
            unique_together=set([('server', 'user'), ('name', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='enumvaluetype',
            unique_together=set([('name', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together=set([('name', 'area')]),
        ),
        migrations.AlterUniqueTogether(
            name='devicetype',
            unique_together=set([('name', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('address', 'server')]),
        ),
        migrations.AlterUniqueTogether(
            name='customservice',
            unique_together=set([('name', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together=set([('name', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together=set([('name', 'house')]),
        ),
    ]
